obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.29, 0.255],[-0.30, 0.255], [-0.30,-0.255], [0.29,-0.255]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
#cost_scaling_factor: 10


observation_sources: scan #camera/depth/points #RosAria/sonar

scan: {sensor_frame: /laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#RosAria/sonar: {sensor_frame: /base_sonar, data_type: PointCloud, topic: /RosAria/sonar, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: rear_sonar, data_type: PointCloud, topic: RosAria/sonar, marking: true, clearing: true}
#camera/depth/points: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: camera/depth/points, marking: true, clearing: true,observation_persistence: 0.0, min_obstacle_height: -0.03, max_obstacle_height: 6}

#camera/depth/points: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: camera/depth/#points, marking: true, clearing: true}
