recovery_behavior_enabled: true
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_rotational_vel: 0.6 #1.0
  min_in_place_rotational_vel: 0.4

  yaw_goal_tolerance: 0.09
  xy_goal_tolerance: 0.15

  acc_lim_th: 2.5 #3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.0 #2.5

  holonomic_robot: false
