acc_lim_x: 2.5
acc_lim_y: 2.5
acc_lim_th: 3.2
max_vel_x: 0.4
min_vel_x: 0.1

max_rotational_vel: 1.0
min_in_place_rotational_vel: 0.4
backup_vel: -0.1

escape_vel: -0.1
holonomic_robot: false

yaw_goal_tolerance: 0.05
xy_goal_tolerance: 0.10
latch_xy_goal_tolerance: false

sim_time: 1.0
sim_granularity: 0.025
angular_sim_granularity: 0.025
vx_samples: 3
vtheta_samples: 20
controller_frequency: 20.0

meter_scoring: false
pdist_scale: 0.6
gdist_scale: 0.8
occdist_scale: 0.01
heading_lookahead: 0.325
heading_scoring: false
heading_scoring_timestep: 0.8
dwa: true
publish_cost_grid_pc: false
global_frame_id: odom

oscillation_reset_dist: 0.05
prune_plan: true
