
transform_tolerance: 0.3
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.29, 0.255],[-0.30, 0.255], [-0.30,-0.255], [0.29,-0.255]]
#robot_radius: ir_of_robot
inflation_radius: 0.50

# BEGIN VOXEL STUFF
observation_sources: scan camera/depth_registered/points #urg_scan 

scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#urg_scan: {sensor_frame: urg_laser, data_type: LaserScan, topic: /urg_scan, marking: true, clearing: true, min_obstacle_height: -0.04, max_obstacle_height: 0.85}

camera/depth_registered/points: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: camera/depth_registered/points, marking: true, clearing: true, min_obstacle_height: 0.15, max_obstacle_height: 0.66, observation_persistance: 2.0}

# END VOXEL STUFF
