obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.29, 0.255],[-0.30, 0.255], [-0.30,-0.255], [0.29,-0.255]]
#robot_radius: ir_of_robot
inflation_radius: 0.50

observation_sources: scan #camera/depth_registered/points

scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#camera/depth_registered/points: {sensor_frame: camera_depth_frame, data_type: #PointCloud2, topic: camera/depth_registered/points, marking: true, clearing: true, #min_obstacle_height: 0.015, max_obstacle_height: 0.90}
