obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.29, 0.255],[-0.30, 0.255], [-0.30,-0.255], [0.29,-0.255]]
#robot_radius: ir_of_robot
inflation_radius: 0.50

observation_sources: scan

scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
